CREATE TABLE IF NOT EXIST LUB_MASTER (
	RECORD_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
	DATE TEXT, CAR_ID INTEGER, 
	LUB_AMOUNT REAL, 
	UNIT_PRICE REAL, 
	ODOMETER REAL, 
	COMMENTS TEXT);

CREATE TABLE IF NOT EXIST COSTS_MASTER (
	RECORD_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
	DATE TEXT, 
	RUNNING_COST REAL);

CREATE TABLE IF NOT EXIST CAR_MASTER (
	CAR_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
	CAR_NAME TEXT, 
	DEFAULT INTEGER);
